/*
 * The MIT License
 *
 * Copyright 2022 Meire de Jesus Torres.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package HighService.Screen;

import HighService.data.Dataconnect;
import java.text.DateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import java.sql.*;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author Meire de Jesus Torres
 */
public class ScreenMain extends javax.swing.JFrame {
//variable to conect database
    Connection cone = null;
   
    public ScreenMain() {
        initComponents();
        cone = Dataconnect.conector();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        lblusername = new javax.swing.JLabel();
        lbldate = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu = new javax.swing.JMenu();
        mencaduser = new javax.swing.JMenuItem();
        menucus = new javax.swing.JMenu();
        mencusinsert = new javax.swing.JMenuItem();
        cusreport = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        meninvsinsert = new javax.swing.JMenuItem();
        menrepinvoice = new javax.swing.JMenuItem();
        menhelp = new javax.swing.JMenu();
        menabout = new javax.swing.JMenuItem();
        mentool = new javax.swing.JMenu();
        menout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HighService");
        setPreferredSize(new java.awt.Dimension(905, 640));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 699, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HighService/icon/HS.png"))); // NOI18N

        lblusername.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblusername.setText("Username");

        lbldate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbldate.setText("Date");

        menu.setText("Menu");

        mencaduser.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mencaduser.setText("User");
        mencaduser.setEnabled(false);
        mencaduser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mencaduserActionPerformed(evt);
            }
        });
        menu.add(mencaduser);

        jMenuBar1.add(menu);

        menucus.setText("Customer");
        menucus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menucusActionPerformed(evt);
            }
        });

        mencusinsert.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mencusinsert.setText("Customer");
        mencusinsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mencusinsertActionPerformed(evt);
            }
        });
        menucus.add(mencusinsert);

        cusreport.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        cusreport.setText("Report");
        cusreport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cusreportActionPerformed(evt);
            }
        });
        menucus.add(cusreport);

        jMenuBar1.add(menucus);

        jMenu3.setText("Invoices");

        meninvsinsert.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        meninvsinsert.setText("Insert Invoice");
        meninvsinsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meninvsinsertActionPerformed(evt);
            }
        });
        jMenu3.add(meninvsinsert);

        menrepinvoice.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menrepinvoice.setText("Report");
        menrepinvoice.setEnabled(false);
        menrepinvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menrepinvoiceActionPerformed(evt);
            }
        });
        jMenu3.add(menrepinvoice);

        jMenuBar1.add(jMenu3);

        menhelp.setText("Help");
        menhelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menhelpActionPerformed(evt);
            }
        });

        menabout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menabout.setText("About");
        menabout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menaboutActionPerformed(evt);
            }
        });
        menhelp.add(menabout);

        jMenuBar1.add(menhelp);

        mentool.setText("Tools");

        menout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menout.setText("Exit");
        menout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menoutActionPerformed(evt);
            }
        });
        mentool.add(menout);

        jMenuBar1.add(mentool);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbldate, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblusername, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lblusername, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbldate, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 346, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(919, 677));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cusreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cusreportActionPerformed
        //CLIENT REPORT
        int report = JOptionPane.showConfirmDialog(null, "Do you want to print Customer report?", "Warning",JOptionPane.YES_NO_OPTION);
        if(report == JOptionPane.YES_OPTION){
            //jasperreports library jasper print
            try {
            JasperPrint print = JasperFillManager.fillReport(getClass().getResourceAsStream("/Reports/report2.jasper"),null,cone);
            JasperViewer.viewReport(print,false);
            } catch (JRException e) {
             JOptionPane.showMessageDialog(null,e);
            }
            
        }
        
    }//GEN-LAST:event_cusreportActionPerformed

    private void meninvsinsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meninvsinsertActionPerformed
        // CALL OBJECT INVOICE SCREEN
        ScreenQuotes invoice = new ScreenQuotes();
        invoice.setVisible(true);
        desktop.add(invoice);
    }//GEN-LAST:event_meninvsinsertActionPerformed

    private void menrepinvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menrepinvoiceActionPerformed
      //invoices report
        int report = JOptionPane.showConfirmDialog(null, "Do you want to print Customer report?", "Warning",JOptionPane.YES_NO_OPTION);
        if(report == JOptionPane.YES_OPTION){
            //jasperreports library jasper print
            try {
            JasperPrint print = JasperFillManager.fillReport(getClass().getResourceAsStream("/Reports/report3.jasper"),null,cone);
            //C:/Final Project/NCI_Project/src/Reports
            JasperViewer.viewReport(print,false);
            } catch (JRException e) {
                JOptionPane.showMessageDialog(null,e);
                // java.lang.NoClassDefFoundError: org/codehaus/groovy/control/CompilationFailedException
            }
            
        }
    }//GEN-LAST:event_menrepinvoiceActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // updating Date and USername
        Date datescre = new Date();
        DateFormat form = DateFormat.getDateInstance(DateFormat.SHORT);
        lbldate.setText(form.format(datescre));
        
    }//GEN-LAST:event_formWindowActivated

    private void menoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menoutActionPerformed
        // BUTTON LOGOUT
        int logout = JOptionPane.showConfirmDialog(null, "Do you want to leave?","Warning",JOptionPane.YES_NO_OPTION);
        if(logout == JOptionPane.YES_OPTION){
            System.exit(0);//EXIT SYSTEM
            
        }
    }//GEN-LAST:event_menoutActionPerformed

    private void menhelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menhelpActionPerformed
        // TODO add your handling code here:

        
    }//GEN-LAST:event_menhelpActionPerformed

    private void menaboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menaboutActionPerformed
        //
        ScreenAbout about = new ScreenAbout();
        about.setVisible(true);
    }//GEN-LAST:event_menaboutActionPerformed

    private void mencaduserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mencaduserActionPerformed
        //CALL OBJECT USER SCREEN
        ScreenUser user = new ScreenUser();
        user.setVisible(true);
        desktop.add(user);
    }//GEN-LAST:event_mencaduserActionPerformed

    private void menucusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menucusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menucusActionPerformed

    private void mencusinsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mencusinsertActionPerformed
                //CALL OBJECT CUSTOMER SCREEN
        ScreenCustomer customer = new ScreenCustomer();
        customer.setVisible(true);
        desktop.add(customer);
    }//GEN-LAST:event_mencusinsertActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScreenMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScreenMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScreenMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScreenMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScreenMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cusreport;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lbldate;
    public static javax.swing.JLabel lblusername;
    private javax.swing.JMenuItem menabout;
    public static javax.swing.JMenuItem mencaduser;
    private javax.swing.JMenuItem mencusinsert;
    private javax.swing.JMenu menhelp;
    private javax.swing.JMenuItem meninvsinsert;
    private javax.swing.JMenuItem menout;
    public static javax.swing.JMenuItem menrepinvoice;
    private javax.swing.JMenu mentool;
    private javax.swing.JMenu menu;
    private javax.swing.JMenu menucus;
    // End of variables declaration//GEN-END:variables
}
